import { test, expect } from "@playwright/test";
import AxeBuilder from "@axe-core/playwright";
import { mkdirSync } from "node:fs";
const routes=["/","/projects","/services","/about","/contact","/projects/rongcheng-city-explorer","/projects/chuangxu-planning-agent","/projects/labellens"];
const widths=[375,390,430,768,1024,1440];

for(const width of widths){test(`render every page without overflow at ${width}px`,async({page})=>{
  await page.setViewportSize({width,height:950});const errors:string[]=[];page.on("pageerror",e=>errors.push(e.message));
  for(const route of routes){const response=await page.goto(route);expect(response?.status()).toBe(200);await page.locator("h1").waitFor();await page.evaluate(()=>document.fonts.ready);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);expect(await page.locator("h1").count()).toBe(1);await page.locator("img").evaluateAll(images=>images.forEach(img=>(img as HTMLImageElement).loading="eager"));await expect.poll(()=>page.locator("img").evaluateAll(images=>images.every(img=>(img as HTMLImageElement).complete&&(img as HTMLImageElement).naturalWidth>0))).toBe(true);mkdirSync("artifacts/screenshots",{recursive:true});await page.screenshot({path:`artifacts/screenshots/${route==="/"?"home":route.slice(1).replaceAll("/","-")}-${width}.png`,fullPage:true});}
  expect(errors).toEqual([]);mkdirSync("artifacts/screenshots",{recursive:true});await page.goto("/");await page.screenshot({path:`artifacts/screenshots/home-${width}.png`,fullPage:true});await page.goto("/contact");await page.screenshot({path:`artifacts/screenshots/contact-${width}.png`,fullPage:true});
});}
test("mobile navigation has predictable focus, escape and working route links",async({page})=>{await page.setViewportSize({width:390,height:844});await page.goto("/");const trigger=page.getByRole("button",{name:"Open navigation"});await trigger.click();await expect(page.getByRole("navigation",{name:"Mobile navigation"}).getByRole("link",{name:"Work",exact:true})).toBeFocused();await page.keyboard.press("Escape");await expect(trigger).toBeFocused();await expect(trigger).toHaveAttribute("aria-expanded","false");await trigger.click();await page.getByRole("navigation",{name:"Mobile navigation"}).getByRole("link",{name:"Services",exact:true}).click();await expect(page).toHaveURL(/\/services$/);await expect(page.getByRole("button",{name:"Open navigation"})).toHaveAttribute("aria-expanded","false");});
test("project filters, case-study links, unknown routes and preview SEO",async({page,request})=>{await page.goto("/projects");await page.getByRole("button",{name:"AI Product",exact:true}).click();await expect(page.locator(".project-card")).toHaveCount(1);await page.getByRole("heading",{name:"Chuangxu Planning Agent"}).getByRole("link").click();await expect(page).toHaveURL(/chuangxu-planning-agent$/);await expect(page.locator('meta[name="robots"]')).toHaveAttribute("content",/noindex/);expect((await page.goto("/projects/unknown"))?.status()).toBe(404);expect((await request.get("/robots.txt")).status()).toBe(200);expect(await (await request.get("/robots.txt")).text()).toContain("Disallow: /");expect(await (await request.get("/sitemap.xml")).text()).not.toContain("labellens");expect((await request.get("/opengraph-image")).headers()["content-type"]).toContain("image/png");});
test("internal links and images are valid",async({page,request})=>{const paths=new Set<string>();for(const route of routes){await page.goto(route);for(const href of await page.locator('a[href^="/"]').evaluateAll(links=>links.map(a=>a.getAttribute("href")!)))paths.add(href.split("#")[0]);}for(const path of paths)expect((await request.get(path)).status(),path).toBe(200);});
test("contact validation, failure preservation and mock provider acceptance",async({page})=>{await page.goto("/contact");await page.getByRole("button",{name:"Tell me about your project",exact:true}).click();await expect(page.locator("#name-error")).toBeVisible();await expect(page.locator("#name")).toBeFocused();await page.getByLabel("Name Required",{exact:true}).fill("Test Founder");await page.getByLabel("Email Required",{exact:true}).fill("founder@example.com");await page.getByLabel("Project type Required",{exact:true}).selectOption("MVP");await page.getByLabel("Tell me about your project Required",{exact:true}).fill("[MOCK_FAILURE] Build a portal for customers and administrators.");await page.getByRole("button",{name:"Tell me about your project",exact:true}).click();await expect(page.getByText("Your inquiry could not be confirmed.",{exact:false})).toBeVisible();await expect(page.locator("#name")).toHaveValue("Test Founder");await page.locator("#description").fill("Build a portal for customers and administrators with a clear user flow.");await page.getByRole("button",{name:"Tell me about your project",exact:true}).click();await expect(page.getByText("Your inquiry has been accepted by the email service.",{exact:false})).toBeVisible();await expect(page.getByRole("button",{name:"Inquiry accepted",exact:true})).toBeDisabled();});
test("copy fallback contains entered brief; reduced motion suppresses transitions",async({page})=>{await page.goto("/contact");await page.locator("#name").fill("Brief owner");await page.locator("#description").fill("A small business website with booking integration.");await page.getByText("View a copyable project brief",{exact:true}).click();await expect(page.locator("#brief")).toHaveValue(/Brief owner/);await page.emulateMedia({reducedMotion:"reduce"});await page.goto("/");expect(await page.locator(".button").first().evaluate(el=>getComputedStyle(el).transitionDuration)).toBe("1e-05s");});
test("all page types pass automated accessibility checks",async({page})=>{for(const route of routes){await page.goto(route);const result=await new AxeBuilder({page}).withTags(["wcag2a","wcag2aa","wcag21aa"]).analyze();expect(result.violations,route).toEqual([]);}});
