import Image from "next/image";
import { PageIntro, ContactCTA, SectionLabel } from "@/components/ui";
import { ContactLinks } from "@/components/contact-links";
import { site } from "@/lib/site";
import { pageMetadata } from "@/lib/metadata";

export const metadata = pageMetadata("About Alson Chua", "Meet Alson Chua, an independent web and app developer based in Malaysia. Product design, frontend development and practical delivery for teams worldwide.", "/about");

export default function About() {
  return <><PageIntro eyebrow="About Alson" title="Good software starts with understanding." description="I enjoy taking an idea apart, understanding how it should work, and turning it into something people can actually use." /><section className="about-page container"><div className="about-story"><p>I’m Alson Chua, an independent web and app developer based in Malaysia, working with clients worldwide.</p><p>My background is in game development. That work gave me experience with programming, interaction design, real-time systems, and the small details that make a product feel responsive and understandable.</p><p>I bring the same systems thinking to websites, web apps, e-commerce, MVPs, dashboards, and AI products: understand the users, define the scope, build the essential workflows, and test how they behave.</p><h2>Modern tools.<br />Personal responsibility.</h2><p>I use modern AI-assisted development tools to accelerate prototyping, implementation, and iteration while personally handling architecture, testing, QA, and deployment.</p><p>My aim is to make progress visible: manageable milestones, clear communication, and a handover that helps you understand the product you’re receiving.</p><p>The selected work is a collection of independent concept projects. Each application gives me a space to explore a distinct industry, visual language, and user journey.</p></div><aside className="profile-panel" aria-label="Developer profile">{site.portrait ? <Image src={site.portrait} width={500} height={500} alt={`Portrait of ${site.name}`} /> : <div className="profile-monogram" aria-hidden="true"><span>ac.</span></div>}<SectionLabel>{site.title}</SectionLabel><h2>{site.name}</h2><p>{site.availability}</p><dl><div><dt>Based in</dt><dd>Malaysia</dd></div><div><dt>Working with</dt><dd>Teams worldwide</dd></div><div><dt>Focus</dt><dd>Web · Apps · Products</dd></div></dl><ContactLinks /></aside></section><section className="about-values container" aria-label="Working principles"><div><h3>Understand first.</h3><p>Get clear on the business problem and the people using the product before deciding what to build.</p></div><div><h3>Keep it practical.</h3><p>Choose architecture and features that serve the current scope and leave room for the next version.</p></div><div><h3>Own the delivery.</h3><p>Take responsibility for implementation, testing, communication, and the final handover.</p></div></section><ContactCTA /></>;
}
