import Image from "next/image";
import Link from "next/link";
import { PageIntro, ContactCTA, SectionLabel } from "@/components/ui";
import { ContactLinks } from "@/components/contact-links";
import { projects } from "@/data/projects";
import { site } from "@/lib/site";
import { pageMetadata } from "@/lib/metadata";

export const metadata = pageMetadata("About Alson Chua", "Alson Chua, an independent web and app developer based in Malaysia. Game-development roots, product design, frontend development, and delivery for teams worldwide.", "/about");

export default function About() {
  return <><PageIntro eyebrow="The person behind the work" title="Curious by nature. A builder by choice." description="Alson Chua / Independent Web & App Developer / Malaysia, working worldwide." /><section className="about-page container"><div className="about-story" data-reveal="up"><h2>From interactive worlds<br />to useful products.</h2><p>My background is in game development: programming, interactive systems, and the details that make an experience feel responsive.</p><p>Today I design and build websites, web applications, stores, and digital products. I connect the visual direction with the way the software works.</p><h3>Modern tools. Personal responsibility.</h3><p>AI-assisted tools help me prototype and iterate. Architecture, implementation, testing, deployment, and handover remain my responsibility.</p><ContactLinks /></div><aside className="profile-panel" aria-label="Developer profile">{site.portrait ? <Image src={site.portrait} width={500} height={500} alt={`Portrait of ${site.name}`} /> : <div className="profile-monogram" aria-hidden="true"><span>ac.</span><small>DESIGN / DEVELOP / DELIVER</small></div>}<SectionLabel>{site.title}</SectionLabel><h2>{site.name}</h2><p>{site.availability}</p><dl><div><dt>Based in</dt><dd>Malaysia</dd></div><div><dt>Working with</dt><dd>Teams worldwide</dd></div><div><dt>Focus</dt><dd>Web · Apps · Products</dd></div></dl></aside></section><section className="about-values container" aria-label="Working principles"><div data-reveal="up"><SectionLabel>01 / Understand</SectionLabel><h3>Start with the problem.</h3><p>Get clear on the users, goals, and scope.</p></div><div data-reveal="up" className="reveal-delay-1"><SectionLabel>02 / Build</SectionLabel><h3>Keep it practical.</h3><p>Choose features and architecture that serve the product.</p></div><div data-reveal="up" className="reveal-delay-2"><SectionLabel>03 / Deliver</SectionLabel><h3>Own the details.</h3><p>Test, communicate, and make the handover clear.</p></div></section><section className="about-projects container"><SectionLabel>Independent concepts / Explore the work</SectionLabel><div>{[projects[0], projects[2], projects[1]].map(project => <Link key={project.slug} href={`/work/${project.slug}`} data-reveal="image"><Image src={project.coverImage} alt={project.coverAlt} width={1440} height={960} sizes="(max-width: 767px) calc(100vw - 40px), 420px" /><span>{project.title}</span></Link>)}</div></section><ContactCTA /></>;
}
